server:
    port: 9761

spring:
    cloud:
        loadbalancer:
            cache:
                enabled: false

eureka:
    instance:
        hostname: 43.201.81.76
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/