server:
    port: 9002

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: soonyeolBio
  application:
    name: crawling-service

eureka:
    instance:
        ip-address: 127.0.0.1
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:9761/eureka/