server:
    port: 9003

spring:
    application:
        name: api-gateway
    cloud:
        loadbalancer:
            cache:
                enabled: false
        gateway:
            routes:
                -   id: asking-service # 구분하기 위한 id값으로 임의로 작성해도 무관
                    predicates: # 조건
                        - Path=/asking/** # first-service/ 으로 요청이 들어오면 
                    uri: lb://ASKING-SERVICE
                    filters:
                        - RewritePath=/asking/(?<segment>.*), /$\{segment} # first-service/ 를 제거하고 요청을 보낸다.
                -   id: asking-swagger
                    predicates:
                        - Path=/v3/api-docs/asking
                    uri: lb://ASKING-SERVICE
                    filters:
                        - RewritePath=/v3/api-docs/asking, /v3/api-docs
                -   id: crawling-service
                    predicates:
                        - Path=/crawling/**
                    uri: lb://CRAWLING-SERVICE
                    filters:
                        - RewritePath=/crawling/(?<segment>.*), /$\{segment}
                -   id: crawling-swagger
                    predicates:
                        - Path=/v3/api-docs/crawling
                    uri: lb://CRAWLING-SERVICE
                    filters:
                        - RewritePath=/v3/api-docs/crawling, /v3/api-docs
            default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Max-Age Access-Control-Request-Headers Access-Control-Request-Method

            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                        - GET
                        - POST
                        - PUT
                        - DELETE
                        - OPTIONS
                        allowedHeaders:
                        - "*"

eureka:
    instance:
        ip-address: 43.201.81.76
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://43.201.81.76:9761/eureka

springdoc:
    swagger-ui:
        path: /swagger